name: Workflow de Integração Contínua

on:
  push:
    branches:
      - feature/LOC-69

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        
      - name: Run npm ci
        run: npm ci

      #- name: Build React app
      #  run: npm run build

      #- name: Run tests
      #  run: npm test

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
       run: npm run test:integration

      - name: Run tests with coverage
       run: npm run test:coverage
